version: "3.9"  # optional since v1.27.0
services:

  bodypix:
    build:
      context: bodypix
    ports:
      - "9000:9000"
    # runtime: nvidia
    user: ${CURRENT_UID}

  capture:
    build:
      context: capture
    depends_on:
      - bodypix
    devices:
      - ${CAMERA}
      - "/dev/video20"
    user: ${CURRENT_UID}
    environment:
      - BACKGROUND_PATH
      - HOLOGRAM
      - CAMERA
